// <auto-generated />
namespace EventusPoc.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DodaniepolaIsAccounted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DodaniepolaIsAccounted));
        
        string IMigrationMetadata.Id
        {
            get { return "201302042104259_Dodanie pola IsAccounted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
